[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r public .next/standalone/public",
  "cp -r .next/static .next/standalone/.next/static"
]

[phases.setup]
nixPkgs = ["nodejs_20"]

[start]
cmd = "node .next/standalone/server.js"
